{
 "title": "Kafka Topics",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "topic", "label": "Topic", "query": "label_values(topic)" }
  ]
 },
 "panels": [
  { "title": "Messages In", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=~\"$topic\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, avg without(instance)((kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=~\"$topic\"}) / (kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=~\"$topic\"})))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum without(instance)(irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=~\"$topic\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=~\"$topic\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Offsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Start Offset",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{job=\"kafka\", topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "End Offset",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{job=\"kafka\", topic=~\"$topic\"}"
    }
   ]
  }
 ]
}