{
 "title": "Kafka Cluster",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_kafkaserver_brokerstate == 3)",
     "legendFormat": "Number of Brokers"
    }
   ]
  },
  {
   "title": "Zookeeper disconnections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(kafka_server_sessionexpirelistener_meanrate{name=\"ZooKeeperExpiresPerSec\",}))"
    }
   ]
  },
  {
   "title": "Unclean elections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Request Pool Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(1 - kafka_server_kafkarequesthandlerpool_meanrate{name=\"RequestHandlerAvgIdlePercent\"})/count(kafka_server_kafkarequesthandlerpool_meanrate{name=\"RequestHandlerAvgIdlePercent\"})"
    }
   ]
  },
  {
   "title": "Network pool usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(1 - kafka_network_socketserver_networkprocessoravgidlepercent)/count(kafka_network_socketserver_networkprocessoravgidlepercent)"
    }
   ]
  },
  { "title": "Topic Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Number of Topics",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount)"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "In-Sync Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_insyncreplicascount)"
    }
   ]
  },
  {
   "title": "Leader Partitions per Broker",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Under-replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Out of sync replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount) - sum(kafka_cluster_partition_insyncreplicascount)"
    }
   ]
  },
  {
   "title": "Total Bytes in",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_meanrate{name=\"BytesInPerSec\",})",
     "legendFormat": "all topics"
    }
   ]
  },
  {
   "title": "Total Bytes out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_meanrate{name=\"BytesOutPerSec\",})",
     "legendFormat": "all topics"
    }
   ]
  },
  {
   "title": "Produced per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_meanrate{job=\"kafka\",name=\"RequestsPerSec\",request=\"Produce\"})",
     "legendFormat": "all topics"
    }
   ]
  },
  {
   "title": "Fetch Consumer per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_meanrate{job=\"kafka\",name=\"RequestsPerSec\",request=\"FetchConsumer\"})",
     "legendFormat": "all topics"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk-space Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_filesystem_size{job='kafka-node', fstype='xfs', mountpoint=~'/var/lib/kafka.*'} - node_filesystem_free{fstype='xfs'}) / node_filesystem_size{fstype='xfs'}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    },
    {
     "expr": "100 * (node_filesystem_size_bytes{fstype='xfs', mountpoint=~'/var/lib/kafka.*'} - node_filesystem_free_bytes{fstype='xfs'}) / node_filesystem_size_bytes{fstype='xfs'}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Number of open files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{job='kafka-node'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JMV Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_operatingsystem_processcpuload {job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(java_lang_memory_heapmemoryusage_used {job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(java_lang_garbagecollector_collectioncount{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}